/**
 * Starter text-only challenge set. The original Go seed was mostly `pronunciation`
 * (audio) entries, which don't apply text-only; kept the two real multiple-choice ones and
 * added more vocabulary/grammar so the learning loop is demoable out of the box.
 *
 * `questionEs`/`explanationEs` are carried over so the "es" translation cache backfills for
 * free; every other language is generated on demand (Fase 3).
 */
import type { LearningChallenge } from '../../shared/types.js';

export const SEED_CHALLENGES: LearningChallenge[] = [
  {
    id: 'ch-dungeon-item',
    type: 'vocabulary',
    question: 'Which item is usually found in a dungeon?',
    questionEs: '¿Qué objeto se encuentra usualmente en una mazmorra?',
    option1: 'Treasure Chest',
    option2: 'Modern Car',
    option3: 'Office Chair',
    correctOption: 1,
    explanationEs: 'Los cofres de tesoro (Treasure Chests) son clásicos en las mazmorras de RPG.',
    tags: ['vocabulary', 'rpg'],
    difficulty: 'beginner',
  },
  {
    id: 'ch-verb-to-be-warrior',
    type: 'grammar',
    question: 'I _____ a brave warrior.',
    questionEs: 'Yo _____ un guerrero valiente.',
    option1: 'am',
    option2: 'is',
    option3: 'are',
    correctOption: 1,
    explanationEs: "Se usa 'am' con el pronombre 'I' (Verb to be).",
    tags: ['grammar', 'basics'],
    difficulty: 'beginner',
  },
  {
    id: 'ch-greeting-morning',
    type: 'vocabulary',
    question: 'How do you greet someone in the morning?',
    questionEs: '¿Cómo saludas a alguien en la mañana?',
    option1: 'Good morning',
    option2: 'Good night',
    option3: 'Goodbye',
    correctOption: 1,
    explanationEs: "'Good morning' se usa para saludar por la mañana.",
    tags: ['vocabulary', 'greetings'],
    difficulty: 'beginner',
  },
  {
    id: 'ch-plural-sword',
    type: 'grammar',
    question: 'The knight carries two _____.',
    questionEs: 'El caballero lleva dos _____.',
    option1: 'swords',
    option2: 'sword',
    option3: 'swordes',
    correctOption: 1,
    explanationEs: "El plural de 'sword' es 'swords' (se añade -s).",
    tags: ['grammar', 'plurals'],
    difficulty: 'beginner',
  },
  {
    id: 'ch-past-defeat',
    type: 'grammar',
    question: 'Yesterday, the hero _____ the dragon.',
    questionEs: 'Ayer, el héroe _____ al dragón.',
    option1: 'defeated',
    option2: 'defeat',
    option3: 'defeating',
    correctOption: 1,
    explanationEs: "En pasado simple, 'defeat' se convierte en 'defeated'.",
    tags: ['grammar', 'past-tense'],
    difficulty: 'intermediate',
  },
  {
    id: 'ch-vocab-potion',
    type: 'vocabulary',
    question: 'You drink a _____ to restore your health.',
    questionEs: 'Bebes una _____ para restaurar tu salud.',
    option1: 'potion',
    option2: 'shield',
    option3: 'map',
    correctOption: 1,
    explanationEs: "Una 'potion' (poción) restaura la salud del personaje.",
    tags: ['vocabulary', 'rpg'],
    difficulty: 'beginner',
  },
  {
    id: 'ch-prep-inside',
    type: 'grammar',
    question: 'The treasure is _____ the chest.',
    questionEs: 'El tesoro está _____ el cofre.',
    option1: 'inside',
    option2: 'between',
    option3: 'around',
    correctOption: 1,
    explanationEs: "'Inside' significa 'dentro de'.",
    tags: ['grammar', 'prepositions'],
    difficulty: 'intermediate',
  },
  {
    id: 'ch-vocab-merchant',
    type: 'vocabulary',
    question: 'Who sells items in the village?',
    questionEs: '¿Quién vende objetos en la aldea?',
    option1: 'The merchant',
    option2: 'The dragon',
    option3: 'The wall',
    correctOption: 1,
    explanationEs: "El 'merchant' (mercader) es quien vende objetos.",
    tags: ['vocabulary', 'rpg'],
    difficulty: 'beginner',
  },
  {
    id: 'ch-question-where',
    type: 'grammar',
    question: '_____ is the nearest town?',
    questionEs: '¿_____ está el pueblo más cercano?',
    option1: 'Where',
    option2: 'Who',
    option3: 'When',
    correctOption: 1,
    explanationEs: "'Where' se usa para preguntar por lugares (dónde).",
    tags: ['grammar', 'questions'],
    difficulty: 'intermediate',
  },
  {
    id: 'ch-vocab-brave',
    type: 'vocabulary',
    question: 'A hero who is not afraid is _____.',
    questionEs: 'Un héroe que no tiene miedo es _____.',
    option1: 'brave',
    option2: 'hungry',
    option3: 'tired',
    correctOption: 1,
    explanationEs: "'Brave' significa 'valiente'.",
    tags: ['vocabulary', 'adjectives'],
    difficulty: 'beginner',
  },
];
