package models

import (
	"time"

	"github.com/google/uuid"
)

// UserChallengeAttempt records a single user answer to a LearningChallenge
type UserChallengeAttempt struct {
	ID             uuid.UUID `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`
	UserID         uuid.UUID `gorm:"type:uuid;not null;index" json:"user_id"`
	ChallengeID    uuid.UUID `gorm:"type:uuid;not null;index" json:"challenge_id"`
	SelectedOption int       `gorm:"not null" json:"selected_option"` // 1, 2 or 3
	IsCorrect      bool      `gorm:"not null;default:false" json:"is_correct"`
	FeedbackAI     string    `gorm:"type:text" json:"feedback_ai,omitempty"` // Generated by Ollama
	AnsweredAt     time.Time `gorm:"not null;default:now()" json:"answered_at"`

	// Relationships
	User      User              `gorm:"foreignKey:UserID" json:"-"`
	Challenge LearningChallenge `gorm:"foreignKey:ChallengeID" json:"-"`
}
